### ISSUE TITLE
Rubyzip failure to allocate memory issue on Windows Server 2008

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-selenium#10]
On Windows Server 2008 & 2008R2 the following exception occurs:      

```
================================================================================
  Error executing action `install` on resource 'chef_gem[rubyzip]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of C:/opscode/chef/embedded/bin/gem install rubyzip -q --no-rdoc --no-ri -v "1.1.7" ----
STDOUT:
  STDERR: [FATAL] failed to allocate memory
---- End output of C:/opscode/chef/embedded/bin/gem install rubyzip -q --no-rdoc --no-ri -v "1.1.7" ----
Ran C:/opscode/chef/embedded/bin/gem install rubyzip -q --no-rdoc --no-ri -v "1.1.7" returned 1
```

This does NOT happen on Windows Server 2012 & 2012 R2.

**Comment by dhoer** [comment]
Rubyzip seems to be the issue:
http://blog.huangzhimin.com/2012/10/02/avoid-using-rubyzip/

I thought the issue was related to winrm.  I even wrote it up as a question:
http://stackoverflow.com/questions/29976315/chef-selenium-rubyzip-failure-to-allocate-memory-issue-on-windows-server-2008/29976316#29976316

But playing with the winrm settings failed to resolve it.

**Comment by dhoer** [comment]
I think I will try powershell to unzip drivers instead of rubyzip:
http://stackoverflow.com/a/26843122/4548096

**Comment by dhoer** [comment]
A better solution expand.exe: https://support.microsoft.com/en-us/kb/80751

**Comment by zopanix** [comment]
@dhoer: FYI, this error is not related to rubyzip itself: https://support.microsoft.com/en-us/help/2786401/cannot-allocate-memory-error-when-you-run-a-shell-script-in-windows-7
I think the worst par is that it still fails today
