### ISSUE TITLE
chromedriver version does not update

### ISSUE THREAD

**Issue by chris-orchard** [dhoer/chef-selenium#11]
This is on Windows.

If I change default['selenium']['chromedriver_version'] to a newer version then re-run the recipe it does not update the chrome driver version.

The chromedriver recipe uses not_if checks on "#{link}/chromedriver.exe" which will exist after the first run. Instead should it check for the dir with the specific version you are trying to provision, updating the existing link if install was required?

**Comment by dhoer** [comment]
Thanks. I will try to have a fix by next week.

**Comment by chris-orchard** [comment]
Great. I'm pretty new to chef but I'm assuming you'll need to change all the:

```
not_if { ::File.exist?("#{link}/chromedriver.exe") }
```

to something that includes the current chromedriver version you're trying to install.

I think you'll also need to change this part so it updates the link to the newer driver if it did update to a newer version when run:

```
link link do
  to dir
  # not_if { ::File.exist?("#{link}") }
end
```

**Comment by dhoer** [comment]
I would like to make it automatically update to the latest version if value was set to 'latest', but selenium is in the process of moving off google groups since it is shutting down.
