### ISSUE TITLE
org.openqa.selenium.WebDriverException: chrome not reachable on CentOS 7.0/Ubuntu 14.04

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-selenium#13]
Opened ticket with ChromeDriver team: 
https://code.google.com/p/chromedriver/issues/detail?id=1109

**Comment by dhoer** [comment]
The issue is caused by running the selenium service as root.  Running service under another user (e.g. selenium) fixes the issue.

**Comment by madskonradsen** [comment]
Thanks! This really helped me!

**Comment by sbartoloti** [comment]
'The issue is caused by running the selenium service as root. Running service under another user (e.g. selenium) fixes the issue.' - can someone please tell me what this really means? 
where and how we can run service under another user? thank you

**Comment by dhoer** [comment]
1. `adduser --system --no-create-home --group USERNAME` creates a system group with the same name as the user and associates it with the user as the primary group. This can then be verified by using the `groups USERNAME` or the `id USERNAME` command.
1. Use the `su - USERNAME` command to switch to the new system account.
1. Start selenium.

See https://github.com/dhoer/chef-selenium/commit/1b261b96fc1b34ee253fe89c729b6201ace297b1#diff-d0898b8a07076828c7812c35a0a2935a for an example of starting up selenium.
