### ISSUE TITLE
Drivers not copied to /selenium/drivers/ folders on Windows 7

### ISSUE THREAD

**Issue by mhemesath** [dhoer/chef-selenium#15]
I updated to the latest 2.4.0 tag and it seems on Windows 7 the IE and chrome drivers do not copy to the correct file location where selenium expects them when running the node recipe.  I confirmed that the drivers are downlaoded to the chef cache, they just are never copied into the selenium driver folder.

Does this work for you? This recipe was working in previous versions so not sure if something on my system changed, or if an update to the recipe broke it.

**Comment by dhoer** [comment]
It is probably related to this change: https://github.com/dhoer/chef-selenium/blob/master/recipes/chromedriver.rb#L26

Does Windows 7 have PowerShell 3?

**Comment by mhemesath** [comment]
Not sure, but if the recipe requires powershell maybe I can add this: https://github.com/opscode-cookbooks/powershell

**Comment by dhoer** [comment]
It looks like Chef introduced powershell_script: https://docs.chef.io/resource_powershell_script.html

I will try to take a look at this issue this weekend.

**Comment by dhoer** [comment]
Thanks for reporting this issue.  Please let me know if this is fixed in latest release.

**Comment by mhemesath** [comment]
Thx for fixing it.. I'll try to run it tomorrow and if not I'll get to it next week (going out of town for a while).
