### ISSUE TITLE
The init scripts are a bit fragile, as they check the pid file but not the actual process

### ISSUE THREAD

**Issue by gggeek** [dhoer/chef-selenium#24]
At least the debian ones...
- if process is dead but pid file is there -> start action will say service is up
- if process is dead but pid file is there -> stop action will fail

**Comment by dhoer** [comment]
I will be happy to accept a pull request with that fix.

**Comment by dhoer** [comment]
Systemd support would also be a welcome PR :wink:

**Comment by gggeek** [comment]
I might try to carve out time for option A, but not B :-D

**Comment by dhoer** [comment]
Would this fix the problem?

```
stop() {
  echo -n "Shutting down <%= @name %> service: "
  kill $(pgrep <%= @home %> -f)
  RETVAL=$?
  if [ ${RETVAL} -eq 0 ]; then
    echo_success
  else
    echo_failure
  fi
  echo
}
```

This uses pgrep to get the pid instead of relying on pid file.

**Comment by dhoer** [comment]
Systemd and upstart are now supported and should be more robust...
