### ISSUE TITLE
Support for Selenium 3

### ISSUE THREAD

**Issue by sterago** [dhoer/chef-selenium#30]
I just tested this cookbook with Selenium 3 (both hub and node) and it works fine, except for one minor problem that causes the node to crash when starting:

`Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Error with the JSON of the config : Deprecated -nodeConfig file encountered. Please update the file to work with Selenium 3. See https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json for more details.`

This can be solved by changing https://github.com/dhoer/chef-selenium/blob/master/templates/default/node_config.erb moving all the keys from the "configuration" node one level up and removing the "configuration" node itself.

I can work on a pull request if this sounds reasonable, but I guess it would make sense to check for the Selenium version being used and use the correct format accordingly?

**Comment by dhoer** [comment]
If you could switch based on major version, that would be great.  A majority of customers I support still want the 2.x version.  Thanks in advance for doing this!
