### ISSUE TITLE
ip:4444/wd/hub show stacktrace

### ISSUE THREAD

**Issue by ramonskie** [dhoer/chef-selenium#4]
i have a strange error when i go to the hub ip:4444/wd/hub
i get the following stacktrace

{"status":13,"value":{"class":"java.lang.NullPointerException","stackTrace":[{"fileName":"ExternalSessionKey.java","className":"org.openqa.grid.internal.ExternalSessionKey","methodName":"fromWebDriverRequest","lineNumber":77},{"fileName":"WebDriverRequest.java","className":"org.openqa.grid.web.servlet.handler.WebDriverRequest","methodName":"extractSession","lineNumber":62},{"fileName":"RequestHandler.java","className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"getSession","lineNumber":237},{"fileName":"RequestHandler.java","className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"process","lineNumber":119},{"fileName":"DriverServlet.java","className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"process","lineNumber":83},{"fileName":"DriverServlet.java","className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"doGet","lineNumber":61},{"fileName":"HttpServlet.java","className":"javax.servlet.http.HttpServlet","methodName":"service","lineNumber":707},{"fileName":"HttpServlet.java","className":"javax.servlet.http.HttpServlet","methodName":"service","lineNumber":820},{"fileName":"ServletHolder.java","className":"org.seleniumhq.jetty7.servlet.ServletHolder","methodName":"handle","lineNumber":565},{"fileName":"ServletHandler.java","className":"org.seleniumhq.jetty7.servlet.ServletHandler","methodName":"doHandle","lineNumber":479},{"fileName":"SessionHandler.java","className":"org.seleniumhq.jetty7.server.session.SessionHandler","methodName":"doHandle","lineNumber":225},{"fileName":"ContextHandler.java","className":"org.seleniumhq.jetty7.server.handler.ContextHandler","methodName":"doHandle","lineNumber":1031},{"fileName":"ServletHandler.java","className":"org.seleniumhq.jetty7.servlet.ServletHandler","methodName":"doScope","lineNumber":406},{"fileName":"SessionHandler.java","className":"org.seleniumhq.jetty7.server.session.SessionHandler","methodName":"doScope","lineNumber":186},{"fileName":"ContextHandler.java","className":"org.seleniumhq.jetty7.server.handler.ContextHandler","methodName":"doScope","lineNumber":965},{"fileName":"ScopedHandler.java","className":"org.seleniumhq.jetty7.server.handler.ScopedHandler","methodName":"handle","lineNumber":117},{"fileName":"HandlerWrapper.java","className":"org.seleniumhq.jetty7.server.handler.HandlerWrapper","methodName":"handle","lineNumber":111},{"fileName":"Server.java","className":"org.seleniumhq.jetty7.server.Server","methodName":"handle","lineNumber":349},{"fileName":"AbstractHttpConnection.java","className":"org.seleniumhq.jetty7.server.AbstractHttpConnection","methodName":"handleRequest","lineNumber":452},{"fileName":"BlockingHttpConnection.java","className":"org.seleniumhq.jetty7.server.BlockingHttpConnection","methodName":"handleRequest","lineNumber":47},{"fileName":"AbstractHttpConnection.java","className":"org.seleniumhq.jetty7.server.AbstractHttpConnection","methodName":"headerComplete","lineNumber":884},{"fileName":"AbstractHttpConnection.java","className":"org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler","methodName":"headerComplete","lineNumber":938},{"fileName":"HttpParser.java","className":"org.seleniumhq.jetty7.http.HttpParser","methodName":"parseNext","lineNumber":634},{"fileName":"HttpParser.java","className":"org.seleniumhq.jetty7.http.HttpParser","methodName":"parseAvailable","lineNumber":230},{"fileName":"BlockingHttpConnection.java","className":"org.seleniumhq.jetty7.server.BlockingHttpConnection","methodName":"handle","lineNumber":66},{"fileName":"SocketConnector.java","className":"org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint","methodName":"run","lineNumber":254},{"fileName":"QueuedThreadPool.java","className":"org.seleniumhq.jetty7.util.thread.QueuedThreadPool","methodName":"runJob","lineNumber":599},{"fileName":"QueuedThreadPool.java","className":"org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3","methodName":"run","lineNumber":534},{"fileName":"Thread.java","className":"java.lang.Thread","methodName":"run","lineNumber":745}]}}

have you seen such errors?
or have any idea how to solve this
because there is nothing in the log files

**Comment by dhoer** [comment]
I have not seen this.  Do you have both a hub and node running?  You have to have both a hub and a node in order for selenium grid to work.  Does running selenium_test cookbook work?  Also, what is the platform and java version?

**Comment by ramonskie** [comment]
ubuntu 14.04
java openjdk 7
i have tested with
hub + node on same vm
hub and node on seperate vms
same results

**Comment by dhoer** [comment]
If you have test kitchen working for you, can you please clone selenium cookbook and run:
```
bundle update
berks update
kitchen test
```
If that fails, can you please past the stacktrace along with output from bundle update and berks update?

**Comment by dhoer** [comment]
Are you using selenium 2.2.2 or 2.2.3?  #3 pull request was to fix some ubuntu issues with 2.2.2.

BTW, I have ran test-kitchen on ubuntu 14.04 multiple time and it has not failed.

**Comment by dhoer** [comment]
@ramonskie After doing some research, it seems like this is expected behavior and shouldn't impact testing:  https://github.com/nicegraham/selenium-grid2-api/blob/master/README.md#wdhub

**Comment by ramonskie** [comment]
thanks it seems thats it. I will look in it.  After my holiday
