### ISSUE TITLE
Don't install unzip if in OSX

### ISSUE THREAD

**Issue by mhemesath** [dhoer/chef-selenium#5]
It seems unzip is already present on OSX and can be removed from the recipe as a package install (it fails to install through homebrew).
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/unzip.1.html

**Comment by dhoer** [comment]
This cookbook doesn't support OSX yet.  I plan to add support for it maybe this summer?  I was planning to create a mac branch and start hacking on it soon.  I have vmware working with a mac image and test-kitchen (see chrome cookbook).  The next step would be figuring out how to configure headless display, etc...

**Comment by mhemesath** [comment]
I can help out with this if you want to create a branch. Otherwise I can just fork this repo and hack on it until I get it.  I have a spare mac I bootstrapped and am testing the recipe on it.

**Comment by dhoer** [comment]
Sure that would be fantastic!  I have created a branch called mac for you.  

FYI, before this branch would be merged, it would have to have chefspec and test-kitchens tests passing for mac.  In case you were interested, VMWare Fusion has a trail version available and Fletcher Nichol wrote a nice gist on how to create a box and configure test-kitchen: https://gist.github.com/fnichol/8609348.

**Comment by dhoer** [comment]
Mac is now officially supported!
