### ISSUE TITLE
Auto Generate Capabilities

### ISSUE THREAD

**Issue by mhemesath** [dhoer/chef-selenium#6]
If you are interested, I wrapped your cookbook and updated it to auto-install the browsers and build the capabilities.  If this is something you are interested in I can contribute this work back.  This allows me to create roles that activate a browser for a given selenium node. Making it super easy to add/remove browsers to a given node without changing any attributes.

``` rb
caps = []
if node['selenium']['node']['chrome']
  include_recipe 'chrome::default'
  caps.push({
      browserName: 'chrome',
      maxInstances: 5,
      seleniumProtocol: 'WebDriver'
  })
end

if node['selenium']['node']['firefox']
  include_recipe "firefox::default"
  caps.push({
      browserName: 'firefox',
      maxInstances: 2,
      seleniumProtocol: 'WebDriver'
  })
end

selenium_node 'selenium_node' do
  hubHost node['selenium']['node']['hubHost']
  capabilities caps
  action :install
end
```

**Comment by dhoer** [comment]
This cookbook was designed with "Separation of Concerns" pattern in mind.  While firefox and chrome maybe a dependency, it is not a direct dependency and therefore not a concern for this cookbook.  This makes the cookbook very flexible with little need to fork it if your environment is different. So if java is baked into your image or you want to use chromium, that doesn't impact this cookbook.

**Comment by dhoer** [comment]
Does that explanation make sense?

**Comment by mhemesath** [comment]
Yup, that makes sense.
