### ISSUE TITLE
selenium_node provider depends on windows

### ISSUE THREAD

**Issue by duckworth** [dhoer/chef-selenium#9]
Trying to use the selenium_node provider on ubuntu 14.04 and it fails unless I include a dependency on the windows cookbook. Seems like the reference to the windows_reboot resource is the issue.

```
[2015-04-10T18:54:26+00:00] ERROR: selenium_node[selenium_node] (my-cookbook::node line 5) 
had an error: 
NoMethodError: No resource or method named `windows_reboot' for `Chef::Provider::SeleniumNode ""'
```

**Comment by dhoer** [comment]
Thanks, I will take a look at that.
